name: Auto Reply to New Issues

on:
  issues:
    types: [opened]

jobs:
  comment-on-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Choose a random comment
        id: random_comment
        run: |
          comments=("Thanks for opening this issue!" "We appreciate your feedback." "We'll look into this issue soon." "Your issue has been noted.")
          echo "comment=${comments[$RANDOM % ${#comments[@]}]}" >> $GITHUB_ENV

      - name: Comment on the issue
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: ${{ env.comment }}

           
